---
- name: install_openstack |Install the latest version of python3-tripleoclient
  dnf:
    name: python3-tripleoclient
    state: latest
  become: True

- name: install_openstack | generate container params
  ansible.builtin.template:
    src: containers_prepare_parameters.yml.j2
    dest: /home/stack/containers_prepare_parameters.yml
    owner: stack
    group: stack
    mode: '0644'
  become: True

- name: install_openstack | Run openstack tripleo container image prepare test
  shell: touch /home/stack/test
  become: True
  become_user: stack
  args:
    chdir: /home/stack

- name: install_openstack | Run openstack tripleo container image prepare 
  shell: openstack tripleo container image prepare -e ~/containers-prepare-parameter.yaml
  become: True
  become_user: stack
  args:
    chdir: /home/stack

- name: install_openstack | generate local network file
  ansible.builtin.template:
    src: undercloud-os-net-config.yaml.j2
    dest: /home/stack/undercloud-os-net-config.yaml
    owner: stack
    group: stack
    mode: '0644'
  become: True

- name: install_openstack | generate undercloud.conf"
  ansible.builtin.template:
    src: undercloud.conf.j2
    dest: /home/stack/undercloud.conf
    owner: stack
    group: stack
    mode: '0644'
  become: True

#- name: install_openstack | Run openstack tripleo container image prepare 

#- name: install_openstack | Run openstack tripleo container image prepare 