- name: "main| Check if we have prepped the server before"
  stat:
    path: "/etc/ostackprepped"
  register: register_trace

- name: "main| prepare director server"
  include_tasks: prepare.yml
  when: not register_trace.stat.exists

- name: "main | install_openstack"
  include_tasks: install_openstack.yml


