---
- name: Set a hostname
  ansible.builtin.hostname:
    name: director

- name: Creates directory
  file:
    path: /home/stack/templates
    state: directory
    owner: stack 
    group: stack 
  become: True

- name: Creates directory
  file:
    path: /home/stack/images
    state: directory
    owner: stack 
    group: stack 
  become: True

- name:  Hostname
  shell: hostnamectl set-hostname undercloud.gec.test
  become: True

- name:  Hostname
  shell: hostnamectl set-hostname --transient undercloud.gec.test
  become: True

- name: Entry in hosts
  lineinfile:
    path: /etc/hosts
    line: "10.0.0.1  undercloud.gec.test undercloud"

##Here an auto subscribe should happen

- name: Same as above but subscribe to a specific pool by ID.
  community.general.redhat_subscription:
    state: present
    username: joe_user
    password: somepass
    pool_ids: {{ poolid }}


