---
- name: "prepare | Add the user 'stack' with a specific uid and a primary group of 'admin'"
  ansible.builtin.user:
    name: stack
    comment: "openstack service account"
    uid: 1666

- name: "prepare |add to sodoers"
  shell: 'echo "stack ALL=(root) NOPASSWD:ALL" | tee -a /etc/sudoers.d/stack'
  become: True

- name: "prepare | add to set perm"
  shell: chmod 0440 /etc/sudoers.d/stack
  become: True

- name: "prepare | Creates directory for templates"
  file:
    path: /home/stack/templates
    state: directory
    owner: stack 
    group: stack 
  become: True

- name: "prepare | Creates directory for templates"
  file:
    path: /home/stack/images
    state: directory
    owner: stack 
    group: stack 
  become: True

- name: "prepare | set hostname #1"
  shell: hostnamectl set-hostname undercloud.gec.test
  become: True

- name: "prepare | set hostname #2"
  shell: hostnamectl set-hostname --transient undercloud.gec.test
  become: True

- name: "prepare | set entry in etc/hosts"
  lineinfile:
    path: /etc/hosts
    line: "10.0.0.1  undercloud.gec.test undercloud"
  become: True

- name: "prepate | Copy script to force registration"
  ansible.builtin.template:
    src: forceregistration.sh.j2
    dest: /usr/local/bin/forceregistration.sh
    owner: root
    group: root
    mode: '0755'

- name: "prepare| Force registration"
  shell: "/usr/local/bin/forceregistration.sh"
  become: True


